import Head from 'next/head';

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">boilerplate!</a>
        </h1>
      </main>
    </div>
  )
}
